### ISSUE TITLE
[Bug]: Harmony failing to patch and causing a crash after some seconds

### ISSUE THREAD

**Issue by Pietrodjaowjao** [LemonLoader/MelonLoader#9] opened 2024-10-02 16:29 UTC
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/17232923/Latest.log)

### Did you attach your log file?

Select an option below

**Comment by TrevTV** [comment] 2024-10-02 19:37
The DotnetAssemblyLoadContextFix error shouldn't hurt anything and the IL Compile Error is normal, as annoying as that is. I don't see any other issues, it's possible the game has an anti-cheat.

**Comment by Pietrodjaowjao** [comment] 2024-10-04 23:37
> The DotnetAssemblyLoadContextFix error shouldn't hurt anything and the IL Compile Error is normal, as annoying as that is. I don't see any other issues, it's possible the game has an anti-cheat.

It has EOS, but literally every other game also crashed so i dont think thats the only issue

**Comment by Pietrodjaowjao** [comment] 2024-10-04 23:38
Every game fails after loading il2cpp.dll support module

**Comment by Pietrodjaowjao** [comment] 2024-10-04 23:39
maybe the issue is missing obb folder?

**Comment by TrevTV** [comment] 2024-10-05 03:41
Checked Among Us which I was able to replicate the crash, but it seems like the issue comes from a stripping bug which I have yet to be able to solve (indicated by the `Unable to find method` logs from Unity). Closing as a duplicate of #8, if you have a different issue with the other apps, feel free to open another issue.

**Closed as completed by TrevTV** 2024-10-05 03:41 UTC
Labels: bug
